name: Update Deployment

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
    
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd client && npm install
    
      - name: Remove .gitignore
        run: rm -rf client/.gitignore

      - name: Generate your content
        run: npm run build:client

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:
          source-directory: client
          target-branch: gh-pages
